name: app_browser_utils
description: Common app browser utils.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.6.0

dependencies:
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.0+2"
  web: