name: app_browser_utils
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  path: ^1.6.0
  process_run:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

dev_dependencies:
  test: ^1.6.0
  dev_build: