name: test_app
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: ^3.9.0

dependencies:
  path: ">=1.9.0"
  tekartik_test_menu_browser:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_browser
      ref: dart3a

dev_dependencies:
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  web:
